### PR TITLE
Add generic 2022 tutorial schematic and pcb

### PR DESCRIPTION
**Pull request by BluCodeGH**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/electrical_tutorials/2)

### CODE REVIEW

**Comment by Rio6** [comment]
Should we add some sort of mounting hole to turn it into a keychain?
but circuit LGTM

**Review by QuantumManiac — DISMISSED** [review]
LGTM! Very cute, and love the name! If the PCB is complete, which it seems to be, be sure to generate gerbers.

**Review by QuantumManiac — APPROVED** [review]
Oh okay, it is complete. Approved!

**Comment by BluCodeGH** [comment]
Added a mounting hole, had to move the test points for it but nothing else changed. Gerbers generated.

**Review by dwkletke — APPROVED** [review]
LGTM! Only one real nit nit (nit<sup>2</sup> if you will): maybe add a label detailing this as a potentiometer? I get the schematic symbol should be self-explanatory but since this is a tutorial board I think it might be useful for new members.
image

**Comment by Artem-Sotnikov** [comment]
Overall, looks good. My only complaint, which is perhaps stylistic, is that the test points on the silkscreen are only labelled as 'POT' and 'GND', without their schematic TP1 and TP2 designators. I think having both on the silkscreen would make the test points easier to identify at a glance and correlate with the schematic. e.g. : 
image

**Review by ZTeper — APPROVED** [review]

**Comment by BluCodeGH** [comment]
@dwkletke @Artem-Sotnikov your comments have been addressed. I'll merge this when I place the JLC order.

**Pull request merged**
